spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 118396605123-568rt48r0vd3s5tm0pd3mah49vfu6q3f.apps.googleusercontent.com
            clientSecret: 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
  datasource:
    url: jdbc:postgresql://localhost/SWIPDATA
    username: postgres
    password: Orel-5287
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  profiles:
    active: dev

server:
  port: 9000
  tomcat:
    relaxed-query-chars: "{,},[,],|"

